hard_tabs = true
max_width = 100
tab_spaces = 3
# imports_indent = "visual"
match_block_trailing_comma = true
# imports_granularity = "module"
# group_imports = "StdExternalCrate"
use_field_init_shorthand = true
