[package]
name = "quest"
version = "0.1.0"
edition = "2021"

[dependencies]
static_assertions = "1.1"
hashbrown = "0.12"
radix_fmt = "1"
once_cell = "1"
qvm-macros = { path = "../macros" }

[dev-dependencies]
assert_matches = "1.5"

[features]
